settings:
  title: 'Status Page'
  url: 'https://stats.oshiro.com.au' # used for Slack messages
  logo: oshiro-studios.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: oshiro-com-au
    name: Oshiro Studios
    description: ''
    url: 'https://oshiro.com.au/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: jtechsystems-com-au
    name: J-Tech Systems
    url: 'https://www.jtechsystems.com.au/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: dillant-com-au
    name: Dillant
    url: 'https://www.dillant.com.au/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: ozservermc-com
    name: OzServer
    url: 'https://www.ozservermc.com/'
    method: GET
    expectStatus: 200
    followRedirect: true
